"""Saving an editor-synchronized belt must not apply its height change twice."""

from copy import deepcopy
import json
from pathlib import Path

from app.application.physical_contracts import normalize_document, template_document, with_belt
from app.schemas.physical_library import CvtDocument


def _replacement(data, height):
    # Build a coherent measured cross-section, not an impossible test belt.
    import math

    belt = data.belt.model_copy(deep=True)
    belt.data.height_m = height
    belt.data.outer_width_m = belt.data.inner_width_m + 2 * height * math.tan(
        belt.data.half_angle_rad
    )
    return belt


def test_synchronized_editor_belt_survives_save_normalization_and_reopen():
    document = template_document("cvts")
    old = document.data
    shaft = (
        old.assembly["geometry"]["primary_outer_radius_at_zero_shift_m"] - old.belt.data.height_m
    )
    belt = _replacement(old, old.belt.data.height_m + 0.001)
    next_data = old.model_copy(deep=True)
    next_data.belt = belt
    geometry = next_data.assembly["geometry"]
    geometry["primary_outer_radius_at_zero_shift_m"] = shaft + belt.data.height_m
    geometry["belt"] = belt.data.model_dump(
        exclude={"outer_length_m", "density_kg_per_m3", "length_reference", "half_angle_rad"}
    )
    geometry["belt_outer_length_m"] = belt.data.outer_length_m
    geometry["sheave_half_angle_rad"] = belt.data.half_angle_rad
    next_data.assembly["inertias"]["belt_density_kg_per_m3"] = belt.data.density_kg_per_m3
    document.data = next_data
    original = deepcopy(document.model_dump())
    once = normalize_document(document)
    twice = normalize_document(once)
    assert once.model_dump() == original
    assert twice.model_dump() == original
    reopened = CvtDocument.model_validate_json(once.model_dump_json())
    assert reopened.model_dump() == original


def test_legacy_choice_only_belt_is_normalized_once():
    document = template_document("cvts")
    old_radius = document.data.assembly["geometry"]["primary_outer_radius_at_zero_shift_m"]
    old_height = document.data.belt.data.height_m
    document.data.belt = _replacement(document.data, old_height + 0.001)
    once = with_belt(document.data)
    assert (
        once.assembly["geometry"]["primary_outer_radius_at_zero_shift_m"]
        == old_radius - old_height + document.data.belt.data.height_m
    )
    assert with_belt(once).model_dump() == once.model_dump()


def test_equal_height_legacy_radius_is_bit_identical():
    document = template_document("cvts")
    document.data.assembly["geometry"][
        "primary_outer_radius_at_zero_shift_m"
    ] = 0.043220283834649065
    assert (
        with_belt(document.data).assembly["geometry"]["primary_outer_radius_at_zero_shift_m"]
        == 0.043220283834649065
    )


def test_actual_frontend_selection_fixture():
    # Generated by editor_foundation_checks.mjs using the production TS adapter.
    from app.schemas.physical_library import BeltChoice, CvtData

    fixture = Path(__file__).parents[2] / "frontend/test/fixtures/belt_selected.json"
    selected = json.loads(fixture.read_text(encoding="utf-8"))
    # The TS fixture carries the affected fields only; use the normal template
    # for unrelated hardware required by CINDER's transport schema.
    data = template_document("cvts").data.model_copy(deep=True)
    data.belt = BeltChoice.model_validate(selected["belt"])
    data.assembly["geometry"].update(selected["assembly"]["geometry"])
    data.assembly["inertias"].update(selected["assembly"]["inertias"])
    data = CvtData.model_validate(data.model_dump())
    before = deepcopy(data.model_dump())
    assert with_belt(data).model_dump() == before
    assert with_belt(with_belt(data)).model_dump() == before
