services:
  backend:
    container_name: cvt-simulator-backend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-gr812b}/cvt-simulator-backend:latest
    # restart: unless-stopped
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - cvt-network
    expose:
      - "8000"

  frontend:
    container_name: cvt-simulator-frontend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-gr812b}/cvt-simulator-frontend:latest
    # restart: unless-stopped
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - cvt-network

networks:
  cvt-network:
    driver: bridge
