# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY backend/requirements.txt .
# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ . 
COPY cvtModel/ ./cvtModel

RUN pip install --no-cache-dir -e ./cvtModel

# Expose port 8000 for the container to listen on
EXPOSE 8000

# Command to run the Python server when the container starts
#CMD ["fastapi", "run" "main.py"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]