from dataclasses import dataclass
from typing import Union


## Pulley stuff
@dataclass
class flyweightForceBreakdown:
    radius: float
    angular_velocity: float
    angle: float

    centrifugal_force: float  # radius, mass, angular velocity
    angle_multiplier: float  # tan(angle)
    net: float


@dataclass
class springCompForceBreakdown:
    compression: float
    net: float


@dataclass
class SpringTorsForceBreakdown:
    rotation: float
    net: float


@dataclass
class HelixForceBreakdown:
    feedbackTorque: float  # TODO: See if this will breakdown
    springTorque: SpringTorsForceBreakdown
    angle: float
    radius: float

    angle_multiplier: float  # The 2 * np.tan(angle) * radius
    net: float


@dataclass
class PrimaryForceBreakdown:
    flyweightForce: flyweightForceBreakdown
    springForce: springCompForceBreakdown
    net: float


@dataclass
class SecondaryForceBreakdown:
    springCompForce: springCompForceBreakdown
    helix_force: HelixForceBreakdown
    net: float


@dataclass
class PrimaryTorqueNumeratorBreakdown:
    clamping_term: float
    load_term: float
    shift_term: float
    net: float


@dataclass
class PrimaryTorqueDenominatorBreakdown:
    inverse_radius_term: float
    inertial_feedback_term: float
    net: float


@dataclass
class PrimaryTorqueBoundsBreakdown:
    tau_lower: float
    tau_upper: float
    numerator: PrimaryTorqueNumeratorBreakdown
    denominator_upper: PrimaryTorqueDenominatorBreakdown
    denominator_lower: PrimaryTorqueDenominatorBreakdown


@dataclass
class SecondaryTorqueNumeratorBreakdown:
    spring_term: float
    load_term: float
    shift_term: float
    net: float


@dataclass
class SecondaryTorqueDenominatorBreakdown:
    inverse_radius_term: float
    helix_feedback_term: float
    inertial_feedback_term: float
    net: float


@dataclass
class SecondaryTorqueBoundsBreakdown:
    tau_negative: float
    tau_positive: float
    numerator: SecondaryTorqueNumeratorBreakdown
    denominator_positive: SecondaryTorqueDenominatorBreakdown
    denominator_negative: SecondaryTorqueDenominatorBreakdown


# All possible pulley breakdown types
PulleyBreakdowns = Union[PrimaryForceBreakdown, SecondaryForceBreakdown]


@dataclass
class PulleyForces:
    """
    Core outputs that every pulley must provide.

    These values are sufficient to drive the CVT simulation regardless
    of the internal mechanism (flyweights, helix, PID, etc.).
    """

    axial_clamping_force: float  # Axial force generated by sheave mechanisms [N]
    axial_centrifugal_from_belt: (
        float  # Axial force contribution from belt centrifugal loading [N]
    )
    axial_force_total: float  # Total axial force on the pulley [N]


@dataclass
class PulleyState:
    """
    Complete pulley state including forces and geometric properties.

    Combines the core forces with geometric data needed for system-level
    calculations (slip model, shift dynamics, etc.).
    """

    forces: PulleyForces

    # Geometric properties at current shift position
    wrap_angle: float  # Belt wrap angle around pulley [rad]
    radius: float  # Effective pitch radius [m]
    angular_velocity: float  # Pulley angular velocity [rad/s]
    angular_position: float  # Pulley angular position [rad]

    # Implementation-specific breakdown (Union of all concrete breakdown types)
    breakdown: PulleyBreakdowns


@dataclass
class CvtDynamicsBreakdown:
    primaryPulleyState: PulleyState
    secondaryPulleyState: PulleyState
    friction: float
    acceleration: float
    cvt_ratio: float
    net: float


## External load
@dataclass
class ExternalLoadForceBreakdown:
    rolling_resistance_force: float
    incline_force: float
    drag_force: float
    net_force_at_car: float
    rolling_resistance_torque_at_secondary: float
    incline_torque_at_secondary: float
    drag_torque_at_secondary: float
    net_torque_at_secondary: float

    @property
    def net(self) -> float:
        return self.net_torque_at_secondary


## Car
@dataclass
class SecondaryPulleyDynamicsBreakdown:
    coupling_torque_at_secondary_pulley: float
    external_load_torque_at_secondary_pulley: float
    external_forces: ExternalLoadForceBreakdown
    secondary_pulley_angular_acceleration: float


## Engine
@dataclass
class PrimaryPulleyDynamicsBreakdown:
    primary_pulley_drive_torque: float
    coupling_torque_at_primary_pulley: float
    power: float
    primary_pulley_angular_velocity: float
    primary_pulley_angular_acceleration: float


# Slip shenanigans
@dataclass
class SlipBreakdown:
    coupling_torque: float
    torque_demand: float
    tau_upper: float
    tau_lower: float
    primary_tau_bounds: PrimaryTorqueBoundsBreakdown
    secondary_tau_bounds: SecondaryTorqueBoundsBreakdown
    effective_cvt_ratio_time_derivative: float
    is_slipping: bool


@dataclass
class BeltStateBreakdown:
    is_stick: bool
    relative_speed: float
    primary_belt_speed: float
    secondary_belt_speed: float
    v_b_star: float
    T_b: float
    v_b: float
    v_b_compatible: float
    v_b_dot: float


## System-level breakdown (single source of truth)
@dataclass
class DrivetrainBreakdown:
    """
    Single source of truth for the entire system state.

    Solves the circular dependency problem by:
    1. Calculating all components in the correct dependency order
    2. Providing a single place to access any component's breakdown
    3. Eliminating duplication while maintaining clean interfaces

    Usage:
        drivetrain = system_model.get_breakdown(state)
        slip_data = drivetrain.belt_slip
        primary_data = drivetrain.primary_pulley
        secondary_data = drivetrain.secondary_pulley
        cvt_data = drivetrain.cvt_dynamics
    """

    belt_slip: SlipBreakdown
    belt_state: BeltStateBreakdown
    primary_pulley: PrimaryPulleyDynamicsBreakdown
    secondary_pulley: SecondaryPulleyDynamicsBreakdown
    cvt_dynamics: CvtDynamicsBreakdown
