"""Entry point for the Ballew (2015) transient comparison."""

from __future__ import annotations

from math import isclose
from pathlib import Path

from belt import build_ballew_geometry, build_equivalent_belt_mapping
from case import (
    build_ballew_assembly,
    build_ballew_inertias,
    build_boundary_setup,
    build_initial_cvt_state,
    build_primary_replay_actuator,
)
from constants import (
    DIRECT_SECONDARY_BOUNDARY_INERTIA_KG_M2,
    PUBLISHED,
    REFLECTED_ATV_TRANSLATION_INERTIA_KG_M2,
)

ROOT = Path(__file__).resolve().parent
REFERENCE = ROOT / "reference"
PRIMARY_FORCE_CSV = REFERENCE / "figure_45_primary_force.csv"
REFERENCE_RPM_CSV = REFERENCE / "figure_41_rpm.csv"


def main() -> None:
    """Audit the reconstruction and, once reference data exist, prepare the run."""

    mapping = build_equivalent_belt_mapping()
    geometry = build_ballew_geometry(mapping)
    inertias = build_ballew_inertias(mapping)
    initial_state = build_initial_cvt_state(geometry)
    boundary_setup = build_boundary_setup()
    del boundary_setup

    _validate_output_inertia()
    _validate_belt_mass(inertias)
    _validate_zero_sheave_axial_mass(inertias)
    _validate_initial_state(geometry, initial_state)

    initial_position = geometry.evaluate(initial_state.shift_position)
    actual_initial_ratio = (
        PUBLISHED.initial_input_rpm / PUBLISHED.initial_output_rpm
    )

    print("Ballew 2015 CINDER simulated-vehicle benchmark")
    print("  case type: fixed input torque + simulated ATV output load (not dyno)")
    print(f"  prescribed input torque: {PUBLISHED.engine_torque_nm:g} N m")
    print(f"  prescribed secondary clamp: {PUBLISHED.output_axial_force_n:g} N")
    print("  primary clamp: Figure 45 time history (manual digitization pending)")
    print("  output torque: generated by reconstructed ATV/road-load boundary")

    print("\nBelt reconstruction (A4)")
    print(
        "  Figure 39 equivalent core [mm]: "
        f"h={mapping.section.height * 1e3:.3f}, "
        f"outer={mapping.section.outer_width * 1e3:.3f}, "
        f"inner={mapping.section.inner_width * 1e3:.3f}, "
        f"cord depth={mapping.section.cord_depth_from_outer * 1e3:.3f}"
    )
    print(
        f"  Ballew effective/nodal path length: "
        f"{mapping.reference_effective_length_m:.9f} m"
    )
    print(f"  CINDER outer path length: {mapping.cinder_outer_length_m:.9f} m")
    print(
        f"  equivalent smooth-section area: "
        f"{mapping.equivalent_cross_sectional_area_m2:.12g} m^2"
    )
    print(
        f"  mass-preserving effective density: "
        f"{mapping.effective_density_kg_per_m3:.6f} kg/m^3"
    )
    print(f"  resolved belt mass: {inertias.belt.mass:.12f} kg")
    print(f"  reconstructed center distance: {geometry.spec.center_distance:.12f} m")
    print(
        "  compatible low-ratio effective radii [mm]: "
        f"rp={mapping.primary_effective_radius_at_zero_shift_m * 1e3:.6f}, "
        f"rs={mapping.secondary_effective_radius_at_zero_shift_m * 1e3:.6f}"
    )

    print("\nClamp/shift mapping (A5)")
    print(
        "  moving-sheave axial masses [kg]: "
        f"primary={inertias.axial_translation.primary_moving_sheave_mass:g}, "
        f"secondary={inertias.axial_translation.secondary_moving_sheave_mass:g}"
    )
    print("  helix: none")
    print("  local sheave clamp balance: algebraic (no sheave axial inertia)")
    print("  belt inertia: retained in CINDER's reduced belt dynamics")

    print("\nInitial state (A3)")
    print(
        f"  shaft speeds: {PUBLISHED.initial_input_rpm:g} / "
        f"{PUBLISHED.initial_output_rpm:g} rpm"
    )
    print(f"  exact speed ratio used: {actual_initial_ratio:.12f}")
    print(f"  Table B1 rounded ratio: {PUBLISHED.initial_ratio:g}")
    print(f"  initial shift: {initial_state.shift_position * 1e3:.9f} mm")
    print(
        "  initial effective radii [mm]: "
        f"rp={initial_position.primary.effective * 1e3:.9f}, "
        f"rs={initial_position.secondary.effective * 1e3:.9f}"
    )
    print(f"  initial belt speed: {initial_state.belt_speed:.9f} m/s")
    print("  initial shift speed: 0 m/s")

    print("\nOutput-side inertia reconstruction (A1/A9)")
    print(
        "  primary boundary inertia: "
        f"{PUBLISHED.input_pulley_and_engine_inertia_kg_m2:g} kg m^2"
    )
    print(
        "  reflected ATV translation inertia: "
        f"{REFLECTED_ATV_TRANSLATION_INERTIA_KG_M2:.9f} kg m^2"
    )
    print(
        "  direct secondary boundary inertia: "
        f"{DIRECT_SECONDARY_BOUNDARY_INERTIA_KG_M2:.9f} kg m^2"
    )

    missing = [
        path.name for path in (PRIMARY_FORCE_CSV, REFERENCE_RPM_CSV) if not path.exists()
    ]
    print("\nRemaining reference data:")
    if missing:
        for filename in missing:
            print(f"  - {filename}")
    else:
        primary_actuator = build_primary_replay_actuator(PRIMARY_FORCE_CSV)
        assembly, _ = build_ballew_assembly(primary_actuator=primary_actuator)
        _validate_replay_assembly(assembly)
        print("  reference CSVs found; Figure 45 replay and full assembly validate")

    print(
        "\nThe five-second integration/overlay is intentionally left disabled until "
        "the Figure 45 and Figure 41 digitizations are supplied."
    )


def _validate_output_inertia() -> None:
    reconstructed = (
        PUBLISHED.output_pulley_inertia_kg_m2
        + REFLECTED_ATV_TRANSLATION_INERTIA_KG_M2
        + DIRECT_SECONDARY_BOUNDARY_INERTIA_KG_M2
    )
    if not isclose(
        reconstructed,
        PUBLISHED.output_pulley_and_atv_inertia_kg_m2,
        rel_tol=0.0,
        abs_tol=1.0e-12,
    ):
        raise RuntimeError("Reconstruction A1 no longer preserves output inertia.")


def _validate_belt_mass(inertias) -> None:
    if not isclose(
        inertias.belt.mass,
        PUBLISHED.belt_mass_kg,
        rel_tol=0.0,
        abs_tol=2.0e-12,
    ):
        raise RuntimeError("Reconstruction A4 no longer preserves the 1 kg belt mass.")


def _validate_zero_sheave_axial_mass(inertias) -> None:
    axial = inertias.axial_translation
    if axial.primary_moving_sheave_mass != 0.0 or axial.secondary_moving_sheave_mass != 0.0:
        raise RuntimeError("Reconstruction A5 requires zero movable-sheave axial mass.")
    if not isclose(axial.belt_mass, PUBLISHED.belt_mass_kg, rel_tol=0.0, abs_tol=2e-12):
        raise RuntimeError("Reconstruction A5 must retain the full belt mass.")


def _validate_initial_state(geometry, state) -> None:
    position = geometry.evaluate(state.shift_position)
    speed_ratio = PUBLISHED.initial_input_rpm / PUBLISHED.initial_output_rpm
    geometry_ratio = position.secondary.effective / position.primary.effective
    if not isclose(geometry_ratio, speed_ratio, rel_tol=0.0, abs_tol=2.0e-11):
        raise RuntimeError("Reconstruction A3 no longer preserves the exact RPM ratio.")
    if state.shift_speed != 0.0:
        raise RuntimeError("Reconstruction A3 requires zero initial shift rate.")


def _validate_replay_assembly(assembly) -> None:
    axial = assembly.inertias.axial_translation
    if axial.primary_moving_sheave_mass != 0.0 or axial.secondary_moving_sheave_mass != 0.0:
        raise RuntimeError("Ballew replay assembly contains unintended sheave axial inertia.")
    if assembly.pulleys.primary.helical_coupling is not None:
        raise RuntimeError("Ballew primary must not contain a helical coupling.")
    if assembly.pulleys.secondary.helical_coupling is not None:
        raise RuntimeError("Ballew secondary must not contain a helical coupling.")


if __name__ == "__main__":
    main()
