/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constants
         * @description Get the physical constants and specifications used by the CVT simulator.
         *     These values are useful for visualization and understanding the simulation parameters.
         *     Calculated values like max_shift and center_to_center are automatically computed.
         */
        get: operations["get_constants_constants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Run CVT simulation with optional custom parameters.
         */
        post: operations["run_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Stream
         * @description Run CVT simulation with streaming progress updates.
         *     Returns newline-delimited JSON (NDJSON) stream with messages:
         *     - StreamProgressMessage: {"type": "progress", "percent": 12.5}
         *     - StreamCompleteMessage: {"type": "complete", "data": {...}}
         *     - StreamErrorMessage: {"type": "error", "message": "..."}
         */
        post: operations["run_stream_run_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Solvers */
        post: operations["run_solvers_solvers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ramp/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Ramp
         * @description Generate preview data for a custom ramp configuration.
         */
        post: operations["preview_ramp_ramp_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllSolverResultsModel */
        AllSolverResultsModel: {
            primary_engagement: components["schemas"]["SolverResultModel"];
            shift_initiation: components["schemas"]["SolverResultModel"];
        };
        /** CarForceBreakdownModel */
        CarForceBreakdownModel: {
            /** Coupling Torque At Secondary Pulley */
            coupling_torque_at_secondary_pulley: number;
            /** External Load Torque At Secondary Pulley */
            external_load_torque_at_secondary_pulley: number;
            external_forces: components["schemas"]["ExternalLoadForceBreakdownModel"];
            /** Secondary Pulley Angular Acceleration */
            secondary_pulley_angular_acceleration: number;
        };
        /**
         * CarSpecs
         * @description Configuration class for CVT simulator car specifications.
         *
         *     Base constants can be overridden to simulate different car configurations.
         *     Calculated constants are computed automatically from base values.
         */
        CarSpecs: {
            /**
             * Engine Inertia
             * @description Engine inertia in kg*m^2
             * @default 0.1
             */
            engine_inertia: number;
            /**
             * Driveline Inertia
             * @description Driveline inertia in kg*m^2 (includes sec CVT, gearbox, axles, wheels, hubs, etc)
             * @default 0.5
             */
            driveline_inertia: number;
            /**
             * Gearbox Ratio
             * @description Gearbox ratio (unitless)
             * @default 7.556
             */
            gearbox_ratio: number;
            /**
             * Wheel Radius
             * @description Wheel radius in meters
             * @default 0.2794
             */
            wheel_radius: number;
            /**
             * Frontal Area
             * @description Frontal area in m^2
             * @default 1.11484
             */
            frontal_area: number;
            /**
             * Drag Coefficient
             * @description Drag coefficient (unitless)
             * @default 0.6
             */
            drag_coefficient: number;
            /**
             * Sheave Angle
             * @description Sheave angle in radians
             * @default 0.40142572795869574
             */
            sheave_angle: number;
            /**
             * Initial Flyweight Radius
             * @description Initial flyweight radius in meters
             * @default 0.05
             */
            initial_flyweight_radius: number;
            /**
             * Helix Radius
             * @description Helix radius in meters
             * @default 0.04445
             */
            helix_radius: number;
            /**
             * Belt Angle
             * @description Belt angle in radians
             * @default 0.24434609527920614
             */
            belt_angle: number;
            /**
             * Belt Height
             * @description Belt height in meters
             * @default 0.0155702
             */
            belt_height: number;
            /**
             * Belt Length
             * @description Belt length in meters
             * @default 0.9532619999999999
             */
            belt_length: number;
            /**
             * Belt Width Top
             * @description Belt width at top in meters
             * @default 0.021589999999999998
             */
            belt_width_top: number;
            /**
             * Min Prim Radius
             * @description Minimum primary pulley radius in meters
             * @default 0.019049999999999997
             */
            min_prim_radius: number;
            /**
             * Max Sec Radius
             * @description Maximum secondary pulley radius in meters
             * @default 0.1016
             */
            max_sec_radius: number;
            /**
             * Initial Sheave Displacement
             * @description Initial sheave displacement in meters
             * @default 0.0063754
             */
            initial_sheave_displacement: number;
            /**
             * Belt Width Bottom
             * @description Belt width at bottom in meters, calculated from top width, height and angle.
             */
            readonly belt_width_bottom: number;
            /**
             * Belt Cross Sectional Area
             * @description Belt cross-sectional area in m^2.
             */
            readonly belt_cross_sectional_area: number;
            /**
             * Max Shift
             * @description Maximum shift distance in meters (calculated constant).
             */
            readonly max_shift: number;
            /**
             * Center To Center
             * @description Center-to-center distance between pulleys in meters (calculated from belt and pulley geometry).
             */
            readonly center_to_center: number;
        };
        /** CircularSegmentConfigModel */
        CircularSegmentConfigModel: {
            /** Length */
            length: number;
            /** Angle Start */
            angle_start: number;
            /** Angle End */
            angle_end: number;
            /** Quadrant */
            quadrant: number;
            /**
             * Type
             * @constant
             */
            type: "circular";
        };
        /** CvtSystemForceBreakdownModel */
        CvtSystemForceBreakdownModel: {
            primaryPulleyState: components["schemas"]["PulleyStateModel"];
            secondaryPulleyState: components["schemas"]["PulleyStateModel"];
            /** Friction */
            friction: number;
            /** Acceleration */
            acceleration: number;
            /** Cvt Ratio */
            cvt_ratio: number;
            /** Net */
            net: number;
        };
        /** EngineForceBreakdownModel */
        EngineForceBreakdownModel: {
            /** Primary Pulley Drive Torque */
            primary_pulley_drive_torque: number;
            /** Coupling Torque At Primary Pulley */
            coupling_torque_at_primary_pulley: number;
            /** Power */
            power: number;
            /** Primary Pulley Angular Velocity */
            primary_pulley_angular_velocity: number;
            /** Primary Pulley Angular Acceleration */
            primary_pulley_angular_acceleration: number;
        };
        /** ExternalLoadForceBreakdownModel */
        ExternalLoadForceBreakdownModel: {
            /** Incline Force */
            incline_force: number;
            /** Drag Force */
            drag_force: number;
            /** Net */
            net: number;
        };
        /** FormattedSimulationResultModel */
        FormattedSimulationResultModel: {
            /** Data */
            data: components["schemas"]["TimeStepDataModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelixForceBreakdownModel */
        HelixForceBreakdownModel: {
            /** Feedbacktorque */
            feedbackTorque: number;
            springTorque: components["schemas"]["SpringTorsForceBreakdownModel"];
            /** Angle */
            angle: number;
            /** Radius */
            radius: number;
            /** Angle Multiplier */
            angle_multiplier: number;
            /** Net */
            net: number;
        };
        /** LinearSegmentConfigModel */
        LinearSegmentConfigModel: {
            /** Length */
            length: number;
            /** Angle */
            angle: number;
            /**
             * Type
             * @constant
             */
            type: "linear";
        };
        /** PiecewiseRampConfigModel */
        PiecewiseRampConfigModel: {
            /** Segments */
            segments: (components["schemas"]["LinearSegmentConfigModel"] | components["schemas"]["CircularSegmentConfigModel"])[];
        };
        /** PrimaryForceBreakdownModel */
        PrimaryForceBreakdownModel: {
            flyweightForce: components["schemas"]["flyweightForceBreakdownModel"];
            springForce: components["schemas"]["springCompForceBreakdownModel"];
            /** Net */
            net: number;
        };
        /** PulleyForcesModel */
        PulleyForcesModel: {
            /** Clamping Force */
            clamping_force: number;
            /** Radial Force */
            radial_force: number;
            /** Max Torque */
            max_torque: number;
        };
        /** PulleyStateModel */
        PulleyStateModel: {
            forces: components["schemas"]["PulleyForcesModel"];
            /** Wrap Angle */
            wrap_angle: number;
            /** Radius */
            radius: number;
            /** Angular Velocity */
            angular_velocity: number;
            /** Angular Position */
            angular_position: number;
            /** Radial From Clamping */
            radial_from_clamping: number;
            /** Radial From Centrifugal */
            radial_from_centrifugal: number;
            /** Breakdown */
            breakdown: components["schemas"]["PrimaryForceBreakdownModel"] | components["schemas"]["SecondaryForceBreakdownModel"];
        };
        /** RampPreviewResponse */
        RampPreviewResponse: {
            /** X */
            x: number[];
            /** Y */
            y: number[];
            /** Slopes */
            slopes: number[];
            /** X Min */
            x_min: number;
            /** X Max */
            x_max: number;
        };
        /** SecondaryForceBreakdownModel */
        SecondaryForceBreakdownModel: {
            springCompForce: components["schemas"]["springCompForceBreakdownModel"];
            helix_force: components["schemas"]["HelixForceBreakdownModel"];
            /** Net */
            net: number;
        };
        /** SimulationArgsInput */
        SimulationArgsInput: {
            /** Flyweight Mass */
            flyweight_mass?: number | null;
            /** Primary Ramp Geometry */
            primary_ramp_geometry?: number | null;
            primary_ramp_config?: components["schemas"]["PiecewiseRampConfigModel"] | null;
            /** Primary Spring Rate */
            primary_spring_rate?: number | null;
            /** Primary Spring Pretension */
            primary_spring_pretension?: number | null;
            /** Secondary Helix Geometry */
            secondary_helix_geometry?: number | null;
            secondary_ramp_config?: components["schemas"]["PiecewiseRampConfigModel"] | null;
            /** Secondary Torsion Spring Rate */
            secondary_torsion_spring_rate?: number | null;
            /** Secondary Compression Spring Rate */
            secondary_compression_spring_rate?: number | null;
            /** Secondary Rotational Spring Pretension */
            secondary_rotational_spring_pretension?: number | null;
            /** Secondary Linear Spring Pretension */
            secondary_linear_spring_pretension?: number | null;
            /** Vehicle Weight */
            vehicle_weight?: number | null;
            /** Driver Weight */
            driver_weight?: number | null;
            /** Traction */
            traction?: number | null;
            /** Angle Of Incline */
            angle_of_incline?: number | null;
            /** Total Distance */
            total_distance?: number | null;
        };
        /** SlipBreakdownModel */
        SlipBreakdownModel: {
            /** Coupling Torque */
            coupling_torque: number;
            /** Torque Demand */
            torque_demand: number;
            /** T Max Prim */
            t_max_prim: number;
            /** T Max Sec */
            t_max_sec: number;
            /** Cvt Ratio Derivative */
            cvt_ratio_derivative: number;
            /** Is Slipping */
            is_slipping: boolean;
        };
        /** SolverResultModel */
        SolverResultModel: {
            /** Success */
            success: boolean;
            /** Value */
            value: number | null;
            /** Units */
            units: string;
            /** Description */
            description: string;
        };
        /** SpringTorsForceBreakdownModel */
        SpringTorsForceBreakdownModel: {
            /** Rotation */
            rotation: number;
            /** Net */
            net: number;
        };
        /** StreamCompleteMessage */
        StreamCompleteMessage: {
            /**
             * Type
             * @constant
             */
            type: "complete";
            data: components["schemas"]["FormattedSimulationResultModel"];
        };
        /** StreamErrorMessage */
        StreamErrorMessage: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Message */
            message: string;
            /** Traceback */
            traceback?: string | null;
        };
        /** StreamProgressMessage */
        StreamProgressMessage: {
            /**
             * Type
             * @constant
             */
            type: "progress";
            /** Percent */
            percent: number;
        };
        /** SystemBreakdownModel */
        SystemBreakdownModel: {
            slip: components["schemas"]["SlipBreakdownModel"];
            engine: components["schemas"]["EngineForceBreakdownModel"];
            car: components["schemas"]["CarForceBreakdownModel"];
            cvt: components["schemas"]["CvtSystemForceBreakdownModel"];
        };
        /** SystemStateModel */
        SystemStateModel: {
            /** Car Velocity */
            car_velocity: number;
            /** Car Position */
            car_position: number;
            /** Shift Velocity */
            shift_velocity: number;
            /** Shift Distance */
            shift_distance: number;
            /** Engine Angular Velocity */
            engine_angular_velocity: number;
            /** Engine Angular Position */
            engine_angular_position: number;
        };
        /** TimeStepDataModel */
        TimeStepDataModel: {
            /** Time */
            time: number;
            state: components["schemas"]["SystemStateModel"];
            system: components["schemas"]["SystemBreakdownModel"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** flyweightForceBreakdownModel */
        flyweightForceBreakdownModel: {
            /** Radius */
            radius: number;
            /** Angular Velocity */
            angular_velocity: number;
            /** Angle */
            angle: number;
            /** Centrifugal Force */
            centrifugal_force: number;
            /** Angle Multiplier */
            angle_multiplier: number;
            /** Net */
            net: number;
        };
        /** springCompForceBreakdownModel */
        springCompForceBreakdownModel: {
            /** Compression */
            compression: number;
            /** Net */
            net: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_constants_constants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarSpecs"];
                };
            };
        };
    };
    run_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormattedSimulationResultModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_run_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamProgressMessage"] | components["schemas"]["StreamCompleteMessage"] | components["schemas"]["StreamErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_solvers_solvers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllSolverResultsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_ramp_ramp_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PiecewiseRampConfigModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RampPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
