/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constants
         * @description Get the physical constants and specifications used by the CVT simulator.
         *     These values are useful for visualization and understanding the simulation parameters.
         *     Calculated values like max_shift, center_to_center, and min/max effective CVT ratio are automatically computed.
         */
        get: operations["get_constants_constants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Run CVT simulation with optional custom parameters.
         */
        post: operations["run_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Stream
         * @description Run CVT simulation with streaming progress updates.
         *     Returns newline-delimited JSON (NDJSON) stream with messages:
         *     - StreamProgressMessage: {"type": "progress", "percent": 12.5}
         *     - StreamCompleteMessage: {"type": "complete", "data": {...}}
         *     - StreamErrorMessage: {"type": "error", "message": "..."}
         */
        post: operations["run_stream_run_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Solvers */
        post: operations["run_solvers_solvers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ramp/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Ramp
         * @description Generate preview data for a custom ramp configuration.
         */
        post: operations["preview_ramp_ramp_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllSolverResultsModel */
        AllSolverResultsModel: {
            primary_engagement: components["schemas"]["SolverResultModel"];
            shift_initiation: components["schemas"]["SolverResultModel"];
        };
        /** AnalysisStepDataModel */
        AnalysisStepDataModel: {
            /** Time */
            time: number;
            state: components["schemas"]["SystemStateModel"];
            derived_state: components["schemas"]["DerivedKinematicStateModel"];
            contact_breakdown: components["schemas"]["ContactDynamicsBreakdownModel"];
        };
        /** BeltWrapBreakdownModel */
        BeltWrapBreakdownModel: {
            /** Wrap Angle */
            wrap_angle: number;
            /** Axial Belt Force */
            axial_belt_force: number;
        };
        /** BranchTorqueResultModel */
        BranchTorqueResultModel: {
            /** Branch */
            branch: string;
            /** Tau P */
            tau_p: number;
            /** Tau S */
            tau_s: number;
        };
        /** CVTGeometryResultModel */
        CVTGeometryResultModel: {
            /** Effective Cvt Ratio */
            effective_cvt_ratio: number;
            /** Effective Cvt Ratio Rate Of Change */
            effective_cvt_ratio_rate_of_change: number;
            /** Primary Outer Radius */
            primary_outer_radius: number;
            /** Primary Effective Radius */
            primary_effective_radius: number;
            /** Primary Centroid Radius */
            primary_centroid_radius: number;
            /** Primary Radius Rate Of Change */
            primary_radius_rate_of_change: number;
            /** Secondary Outer Radius */
            secondary_outer_radius: number;
            /** Secondary Effective Radius */
            secondary_effective_radius: number;
            /** Secondary Centroid Radius */
            secondary_centroid_radius: number;
            /** Secondary Radius Rate Of Change */
            secondary_radius_rate_of_change: number;
            /** Primary Wrap Angle */
            primary_wrap_angle: number;
            /** Secondary Wrap Angle */
            secondary_wrap_angle: number;
        };
        /**
         * CarSpecs
         * @description Configuration class for CVT simulator car specifications.
         *
         *     Base constants can be overridden to simulate different car configurations.
         *     Calculated constants are computed automatically from base values.
         */
        CarSpecs: {
            /**
             * Engine Inertia
             * @description Engine inertia in kg*m^2
             * @default 0.1
             */
            engine_inertia: number;
            /**
             * Secondary Inertia
             * @description Secondary CVT pulley inertia in kg*m^2
             * @default 0.1
             */
            secondary_inertia: number;
            /**
             * Gearbox Inertia
             * @description Gearbox inertia in kg*m^2
             * @default 0.05
             */
            gearbox_inertia: number;
            /**
             * Wheel Inertia
             * @description Wheel inertia in kg*m^2 (all wheels)
             * @default 0.2
             */
            wheel_inertia: number;
            /**
             * Driveline Inertia
             * @description Driveline inertia in kg*m^2 (includes sec CVT, gearbox, axles, wheels, hubs, etc)
             * @default 0.5
             */
            driveline_inertia: number;
            /**
             * Gearbox Ratio
             * @description Gearbox ratio (unitless)
             * @default 7.556
             */
            gearbox_ratio: number;
            /**
             * Wheel Radius
             * @description Wheel radius in meters
             * @default 0.2794
             */
            wheel_radius: number;
            /**
             * Frontal Area
             * @description Frontal area in m^2
             * @default 1.11484
             */
            frontal_area: number;
            /**
             * Drag Coefficient
             * @description Drag coefficient (unitless)
             * @default 0.6
             */
            drag_coefficient: number;
            /**
             * Rolling Resistance Coefficient
             * @description Rolling resistance coefficient (unitless)
             * @default 0.015
             */
            rolling_resistance_coefficient: number;
            /**
             * Sheave Angle
             * @description Sheave angle in radians
             * @default 0.40142572795869574
             */
            sheave_angle: number;
            /**
             * Initial Flyweight Radius
             * @description Initial flyweight radius in meters
             * @default 0.04878
             */
            initial_flyweight_radius: number;
            /**
             * Helix Radius
             * @description Helix radius in meters
             * @default 0.04445
             */
            helix_radius: number;
            /**
             * Belt Height
             * @description Belt height in meters
             * @default 0.0155702
             */
            belt_height: number;
            /**
             * Belt Length
             * @description Belt length in meters
             * @default 0.9532619999999999
             */
            belt_length: number;
            /**
             * Belt Width Top
             * @description Belt width at top in meters
             * @default 0.021335999999999997
             */
            belt_width_top: number;
            /**
             * Belt Width Bottom
             * @description Belt width at bottom in meters
             * @default 0.0168148
             */
            belt_width_bottom: number;
            /**
             * Min Prim Radius
             * @description Minimum primary pulley radius in meters
             * @default 0.0206375
             */
            min_prim_radius: number;
            /**
             * Max Sec Radius
             * @description Maximum secondary pulley radius in meters
             * @default 0.1016
             */
            max_sec_radius: number;
            /**
             * Initial Sheave Displacement
             * @description Initial sheave displacement in meters
             * @default 0.0024891999999999996
             */
            initial_sheave_displacement: number;
            /**
             * Belt Angle
             * @description Belt width at bottom in meters, calculated from top width, height and angle.
             */
            readonly belt_angle: number;
            /**
             * Belt Cross Sectional Area
             * @description Belt cross-sectional area in m^2.
             */
            readonly belt_cross_sectional_area: number;
            /**
             * Max Shift
             * @description Maximum shift distance in meters (calculated constant).
             */
            readonly max_shift: number;
            /**
             * Center To Center
             * @description Center-to-center distance between pulleys in meters (calculated from belt and pulley geometry).
             */
            readonly center_to_center: number;
            /**
             * Min Effective Cvt Ratio
             * @description Minimum effective CVT ratio (unitless) at zero shift distance.
             */
            readonly min_effective_cvt_ratio: number;
            /**
             * Max Effective Cvt Ratio
             * @description Maximum effective CVT ratio (unitless) at max shift distance.
             */
            readonly max_effective_cvt_ratio: number;
        };
        /** CircularSegmentConfigModel */
        CircularSegmentConfigModel: {
            /** Length */
            length: number;
            /** Angle Start */
            angle_start: number;
            /** Angle End */
            angle_end: number;
            /** Quadrant */
            quadrant: number;
            /**
             * Type
             * @constant
             */
            type: "circular";
        };
        /** ContactDynamicsBreakdownModel */
        ContactDynamicsBreakdownModel: {
            contact: components["schemas"]["ContactTorqueResultModel"];
            drivetrain: components["schemas"]["DrivetrainAccelerationBreakdownModel"];
            shift: components["schemas"]["CvtDynamicsBreakdownModel"];
            geometry: components["schemas"]["CVTGeometryResultModel"];
        };
        /** ContactTorqueResultModel */
        ContactTorqueResultModel: {
            /** Tau P */
            tau_p: number;
            /** Tau S */
            tau_s: number;
            /** Branch */
            branch: string;
            slip_metrics: components["schemas"]["SlipMetricsResultModel"];
            branch_result: components["schemas"]["BranchTorqueResultModel"];
        };
        /** CvtDynamicsBreakdownModel */
        CvtDynamicsBreakdownModel: {
            primaryPulleyState: components["schemas"]["PulleyForcesModel"];
            secondaryPulleyState: components["schemas"]["PulleyForcesModel"];
            /** Friction */
            friction: number;
            /** Acceleration */
            acceleration: number;
            /** Net */
            net: number;
        };
        /** DerivedKinematicStateModel */
        DerivedKinematicStateModel: {
            /** Car Velocity */
            car_velocity: number;
            /** Car Position */
            car_position: number;
            /** Belt Position */
            belt_position: number;
            /** Engine Angular Velocity */
            engine_angular_velocity: number;
            /** Engine Angular Position */
            engine_angular_position: number;
        };
        /** DrivetrainAccelerationBreakdownModel */
        DrivetrainAccelerationBreakdownModel: {
            /** Ω P Dot */
            "\u03C9_p_dot": number;
            /** Ω S Dot */
            "\u03C9_s_dot": number;
            /** V B Dot */
            v_b_dot: number;
            engine_breakdown: components["schemas"]["EngineTorqueBreakdownModel"];
            external_load_breakdown: components["schemas"]["ExternalLoadForceBreakdownModel"];
            /** Tau P */
            tau_p: number;
            /** Tau S */
            tau_s: number;
        };
        /** EngineTorqueBreakdownModel */
        EngineTorqueBreakdownModel: {
            /** Engine Torque */
            engine_torque: number;
            /** Engine Speed */
            engine_speed: number;
            /** Engine Power */
            engine_power: number;
        };
        /** ExternalLoadForceBreakdownModel */
        ExternalLoadForceBreakdownModel: {
            /** Rolling Resistance Force */
            rolling_resistance_force: number;
            /** Incline Force */
            incline_force: number;
            /** Drag Force */
            drag_force: number;
            /** Net Force At Car */
            net_force_at_car: number;
            /** Rolling Resistance Torque At Secondary */
            rolling_resistance_torque_at_secondary: number;
            /** Incline Torque At Secondary */
            incline_torque_at_secondary: number;
            /** Drag Torque At Secondary */
            drag_torque_at_secondary: number;
            /** Net Torque At Secondary */
            net_torque_at_secondary: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelixForceBreakdownModel */
        HelixForceBreakdownModel: {
            /** Feedbacktorque */
            feedbackTorque: number;
            springTorque: components["schemas"]["SpringTorsForceBreakdownModel"];
            /** Angle */
            angle: number;
            /** Radius */
            radius: number;
            /** Angle Multiplier */
            angle_multiplier: number;
            /** Net */
            net: number;
        };
        /** LinearSegmentConfigModel */
        LinearSegmentConfigModel: {
            /** Length */
            length: number;
            /** Angle */
            angle: number;
            /**
             * Type
             * @constant
             */
            type: "linear";
        };
        /** NoSlipBreakdownModel */
        NoSlipBreakdownModel: {
            /** R P */
            r_p: number;
            /** R S */
            r_s: number;
            /** R P Dot */
            r_p_dot: number;
            /** R S Dot */
            r_s_dot: number;
            /** Tau Engine Over R P */
            tau_engine_over_r_p: number;
            /** Tau Load Over R S */
            tau_load_over_r_s: number;
            /** Primary Inertia Term */
            primary_inertia_term: number;
            /** Secondary Inertia Term */
            secondary_inertia_term: number;
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
        };
        /** NoSlipResultModel */
        NoSlipResultModel: {
            /** V B Dot Ns */
            v_b_dot_ns: number;
            /** Tau P Ns */
            tau_p_ns: number;
            /** Tau S Ns */
            tau_s_ns: number;
            breakdown: components["schemas"]["NoSlipBreakdownModel"];
        };
        /** PiecewiseRampConfigModel */
        PiecewiseRampConfigModel: {
            /** Segments */
            segments: (components["schemas"]["LinearSegmentConfigModel"] | components["schemas"]["CircularSegmentConfigModel"])[];
        };
        /** PrimaryForceBreakdownModel */
        PrimaryForceBreakdownModel: {
            flyweightForce: components["schemas"]["flyweightForceBreakdownModel"];
            springForce: components["schemas"]["springCompForceBreakdownModel"];
            /** Net */
            net: number;
        };
        /** PrimaryTorqueAdmissibilityBreakdownModel */
        PrimaryTorqueAdmissibilityBreakdownModel: {
            /** Shift Distance */
            shift_distance: number;
            /** Wrap Angle */
            wrap_angle: number;
            /** Effective Radius */
            effective_radius: number;
            /** Centroid Radius */
            centroid_radius: number;
            /** Centroid Radius Rate */
            centroid_radius_rate: number;
            /** Axial Clamping Force */
            axial_clamping_force: number;
            /** Belt Centripetal Term */
            belt_centripetal_term: number;
            /** Friction Coefficient */
            friction_coefficient: number;
            /** Sheave Half Angle */
            sheave_half_angle: number;
            /** Tau P Stick Limit */
            tau_p_stick_limit: number;
            /** Tau P Stick Upper */
            tau_p_stick_upper: number;
            /** Tau P Stick Lower */
            tau_p_stick_lower: number;
        };
        /** PulleyForcesModel */
        PulleyForcesModel: {
            /** Pulley Breakdown */
            pulley_breakdown: components["schemas"]["PrimaryForceBreakdownModel"] | components["schemas"]["SecondaryForceBreakdownModel"];
            belt_wrap: components["schemas"]["BeltWrapBreakdownModel"];
            /** Net */
            net: number;
        };
        /** RampPreviewResponse */
        RampPreviewResponse: {
            /** X */
            x: number[];
            /** Y */
            y: number[];
            /** Slopes */
            slopes: number[];
            /** X Min */
            x_min: number;
            /** X Max */
            x_max: number;
        };
        /** SecondaryForceBreakdownModel */
        SecondaryForceBreakdownModel: {
            springCompForce: components["schemas"]["springCompForceBreakdownModel"];
            helix_force: components["schemas"]["HelixForceBreakdownModel"];
            /** Net */
            net: number;
        };
        /** SecondaryTorqueAdmissibilityBreakdownModel */
        SecondaryTorqueAdmissibilityBreakdownModel: {
            /** Shift Distance */
            shift_distance: number;
            /** Wrap Angle */
            wrap_angle: number;
            /** Effective Radius */
            effective_radius: number;
            /** Centroid Radius */
            centroid_radius: number;
            /** Centroid Radius Rate */
            centroid_radius_rate: number;
            /** Helix Rotation */
            helix_rotation: number;
            /** Helix Rotation Rate */
            helix_rotation_rate: number;
            /** Spring Torsion Term */
            spring_torsion_term: number;
            /** Spring Comp Term */
            spring_comp_term: number;
            /** Belt Centripetal Term */
            belt_centripetal_term: number;
            /** Friction Coefficient */
            friction_coefficient: number;
            /** Sheave Half Angle */
            sheave_half_angle: number;
            /** Denominator Upper */
            denominator_upper: number;
            /** Denominator Lower */
            denominator_lower: number;
            /** Tau Stick Upper */
            tau_stick_upper: number;
            /** Tau Stick Lower */
            tau_stick_lower: number;
        };
        /** SimulationAnalysisResultModel */
        SimulationAnalysisResultModel: {
            /** Data */
            data: components["schemas"]["AnalysisStepDataModel"][];
            termination: components["schemas"]["SimulationTerminationContextModel"];
        };
        /** SimulationArgsInput */
        SimulationArgsInput: {
            /** Flyweight Mass */
            flyweight_mass?: number | null;
            primary_ramp_config?: components["schemas"]["PiecewiseRampConfigModel"] | null;
            /** Primary Spring Rate */
            primary_spring_rate?: number | null;
            /** Primary Spring Pretension */
            primary_spring_pretension?: number | null;
            secondary_ramp_config?: components["schemas"]["PiecewiseRampConfigModel"] | null;
            /** Secondary Torsion Spring Rate */
            secondary_torsion_spring_rate?: number | null;
            /** Secondary Compression Spring Rate */
            secondary_compression_spring_rate?: number | null;
            /** Secondary Rotational Spring Pretension */
            secondary_rotational_spring_pretension?: number | null;
            /** Secondary Linear Spring Pretension */
            secondary_linear_spring_pretension?: number | null;
            /** Vehicle Weight */
            vehicle_weight?: number | null;
            /** Driver Weight */
            driver_weight?: number | null;
            /** Traction */
            traction?: number | null;
            /** Angle Of Incline */
            angle_of_incline?: number | null;
            /** Total Distance */
            total_distance?: number | null;
        };
        /** SimulationTerminationContextModel */
        SimulationTerminationContextModel: {
            /** Reason Code */
            reason_code: string;
            /** Reason */
            reason: string;
            /** Mode */
            mode: string;
            /** Final Time */
            final_time: number;
            /** Reached Max Time */
            reached_max_time: boolean;
            /** Event */
            event: string | null;
            /** Event Time */
            event_time: number | null;
            /** Transition Count */
            transition_count: number;
            /** Max Transitions */
            max_transitions: number;
            /** Details */
            details: {
                [key: string]: number | string | boolean;
            };
        };
        /** SlipMetricsResultModel */
        SlipMetricsResultModel: {
            /** Primary Relative Speed */
            primary_relative_speed: number;
            /** Secondary Relative Speed */
            secondary_relative_speed: number;
            /** Primary Slip Direction */
            primary_slip_direction: number;
            /** Secondary Slip Direction */
            secondary_slip_direction: number;
            /** Primary Admissible */
            primary_admissible: boolean;
            /** Secondary Admissible */
            secondary_admissible: boolean;
            admissibility: components["schemas"]["TorqueAdmissibilityResultModel"];
            no_slip: components["schemas"]["NoSlipResultModel"];
        };
        /** SolverResultModel */
        SolverResultModel: {
            /** Success */
            success: boolean;
            /** Value */
            value: number | null;
            /** Units */
            units: string;
            /** Description */
            description: string;
        };
        /** SpringTorsForceBreakdownModel */
        SpringTorsForceBreakdownModel: {
            /** Rotation */
            rotation: number;
            /** Net */
            net: number;
        };
        /** StreamCompleteMessage */
        StreamCompleteMessage: {
            /**
             * Type
             * @constant
             */
            type: "complete";
            data: components["schemas"]["SimulationAnalysisResultModel"];
        };
        /** StreamErrorMessage */
        StreamErrorMessage: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Message */
            message: string;
            /** Traceback */
            traceback?: string | null;
        };
        /** StreamProgressMessage */
        StreamProgressMessage: {
            /**
             * Type
             * @constant
             */
            type: "progress";
            /** Percent */
            percent: number;
        };
        /** SystemStateModel */
        SystemStateModel: {
            /** S */
            s: number;
            /** S Dot */
            s_dot: number;
            /** Ω P */
            "\u03C9_p": number;
            /** Ω S */
            "\u03C9_s": number;
            /** V B */
            v_b: number;
        };
        /** TorqueAdmissibilityResultModel */
        TorqueAdmissibilityResultModel: {
            primary: components["schemas"]["PrimaryTorqueAdmissibilityBreakdownModel"];
            secondary: components["schemas"]["SecondaryTorqueAdmissibilityBreakdownModel"];
            /** Primary Tau P Stick Upper */
            primary_tau_p_stick_upper: number;
            /** Primary Tau P Stick Lower */
            primary_tau_p_stick_lower: number;
            /** Secondary Tau Stick Upper */
            secondary_tau_stick_upper: number;
            /** Secondary Tau Stick Lower */
            secondary_tau_stick_lower: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** flyweightForceBreakdownModel */
        flyweightForceBreakdownModel: {
            /** Radius */
            radius: number;
            /** Angular Velocity */
            angular_velocity: number;
            /** Angle */
            angle: number;
            /** Centrifugal Force */
            centrifugal_force: number;
            /** Angle Multiplier */
            angle_multiplier: number;
            /** Net */
            net: number;
        };
        /** springCompForceBreakdownModel */
        springCompForceBreakdownModel: {
            /** Compression */
            compression: number;
            /** Net */
            net: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_constants_constants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarSpecs"];
                };
            };
        };
    };
    run_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationAnalysisResultModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_run_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamProgressMessage"] | components["schemas"]["StreamCompleteMessage"] | components["schemas"]["StreamErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_solvers_solvers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationArgsInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllSolverResultsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_ramp_ramp_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PiecewiseRampConfigModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RampPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
