import '@styles/_base.scss';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { App } from '@pages/app/App';
import { LoadingProvider } from '@contexts/LoadingContext';
import { SimulationCaseProvider } from '@contexts/SimulationCaseContext';
import { SimulationRunProvider } from '@contexts/SimulationRunContext';
const root = document.getElementById('root');
if (root === null) throw new Error('Root element not found.');
createRoot(root).render(<StrictMode><SimulationCaseProvider><SimulationRunProvider><LoadingProvider><BrowserRouter><App /></BrowserRouter></LoadingProvider></SimulationRunProvider></SimulationCaseProvider></StrictMode>);
