name: CI for Python and C# Project

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  python-tests:
    name: Python Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 src test

      - name: Run black (check)
        run: |
          source venv/bin/activate
          black --check src test

      - name: Run Python unit tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test

  csharp-tests:
    name: C# Build & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET Environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Adjust if needed

      - name: Restore .NET dependencies
        run: dotnet restore src/frontend/CommunicationProtocol/CommunicationProtocol.csproj

      - name: Build CommunicationProtocol project
        run: dotnet build src/frontend/CommunicationProtocol/CommunicationProtocol.csproj --configuration Release --no-restore

      - name: Run C# unit tests
        run: dotnet test src/frontend/CommunicationProtocolUnitTesting/CommunicationProtocolUnitTesting.csproj --configuration Release --no-build
