name: CI for Python Project

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 src test

      - name: Run black (check)
        run: |
          source venv/bin/activate
          black --check src test

      - name: Run unit tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore .NET dependencies
        run: dotnet restore src/frontend/CommunicationProtocol/CommunicationProtocol.csproj --configuration Release
      
      - name: Build C# project
        run: dotnet build src/frontend/CommunicationProtocol/CommunicationProtocol.csproj --configuration Release --no-restore

      - name: Run C# unit tests
        run: dotnet test src/frontend/CommunicationProtocolUnitTests/CommunicationProtocolUnitTests.csproj --configuration Release --no-build

